# Set how many application instances to run.
replicaCount: 1

# Override these settings and use your container image.
image:
  repository: alexandreroman/hello
  tag: latest
  pullPolicy: IfNotPresent

# Set image pull secrets (in case you're using a private container registry).
imageCredentials:
  registry: # gcr.io
  username: # oauth2accesstoken
  password: # $(gcloud auth print-access-token)

# Set service type: LoadBalancer, ClusterIP, NodePort
service:
  type: LoadBalancer
  port: 80

# Set to false to disable Prometheus support.
monitoring: true

# Set to false to disable Spring Cloud Kubernetes support.
sck: true

# Set configuration properties.
config:
  foo: bar
