kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "spring-boot.fullname" . }}
data:
  application.yml: |-
    {{- range $key, $val := .Values.config }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
