kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "spring-boot.fullname" . }}-role
rules:
- apiGroups: [""]
  resources: ["services", "pods", "configmaps", "endpoints", "secrets"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default:{{ include "spring-boot.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: ClusterRole
  name: {{ include "spring-boot.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
